version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tribuna360
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"  # Exposición del puerto
    networks:
      - tribuna360_network

  backend:
    build: ./backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/tribuna360
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
    depends_on:
      - db
    networks:
      - tribuna360_network

networks:
  tribuna360_network:
    driver: bridge

